version: "3"
services:
  apache:
    depends_on:
      - php
      - db
    networks:
      - frontend
      - backend
    build:
      context: ./apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
  php:
    build: ./php
    networks:
      - backend
    volumes:
      - ./www:/var/www/html
  db:
    image: mariadb:10.4
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=local
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    networks:
      - backend
  mailhog:
    image: skilldlabs/mailhog:latest
    ports:
      - "8025:8025"
networks:
  frontend:
  backend: